# Generated by Django 2.1.1 on 2019-03-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbacdemo', '0002_auto_20190301_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
